### ISSUE TITLE
Permutation test from Ch 16

### ISSUE THREAD

**Issue by bonnfire** [Amherst-Statistics/IPS9inR#10]
e79ad8a3e12887d0fbaded1e9cd0e29d016379b9

Reprex: 
```
DRP <- read_csv("https://nhorton.people.amherst.edu/ips9/data/chapter16/EG16-11DRP.csv")
Treatment <- DRP %>%
  filter(group == "Treatment")
Control <- DRP %>% 
  filter(group == "Control")

diffMeanDRP <- function(Treatment, Control){
 Sample_Treatment <- resample(Treatment)
 Sample_Control<- resample(Control)
 diff(c(mean(~ drp, data = Sample_Treatment), mean(~ drp, data = Sample_Control)))
}
numsim <- 10
DRP_sim <- do(numsim) * diffMeanDRP(sample(Treatment), Control)
```

**Comment by nicholasjhorton** [comment]
Here's a cleaner approach:

DRP <- read_csv("https://nhorton.people.amherst.edu/ips9/data/chapter16/EG16-11DRP.csv")
diffmean(drp ~ group, data = DRP)
favstats(drp ~ group, data = DRP)
res <- do(100) * diffmean(drp ~ shuffle(group), data = DRP)
favstats(~ diffmean, data = res)

Does that address your query?

Nick

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000
