### ISSUE TITLE
ch.6 EX6.17 and EX6.18 

### ISSUE THREAD

**Issue by shukryzablah** [Amherst-Statistics/IPS9inR#14]
I'm unsure what to do for ex6.17 and ex6.18 starting at page 375. The datasets available for both examples are read into R below. 

Is there anything to include for these two? 

``` r
library(readr)

PBTest <- read_csv("https://nhorton.people.amherst.edu/ips9/data/chapter06/EG06-17PBTEST.csv")
#> Parsed with column specification:
#> cols(
#>   conc = col_double()
#> )
PBTest
#> # A tibble: 3 x 1
#>    conc
#>   <dbl>
#> 1  6.79
#> 2  6.13
#> 3  7.17

PBTest2 <- read_csv("https://nhorton.people.amherst.edu/ips9/data/chapter06/EG06-18PBTEST.csv")
#> Parsed with column specification:
#> cols(
#>   conc = col_double()
#> )
PBTest2
#> # A tibble: 3 x 1
#>    conc
#>   <dbl>
#> 1  6.79
#> 2  6.13
#> 3  7.17
```

Created on 2018-07-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by nicholasjhorton** [comment]
Can you please provide a bit more background (as I don't have access to the textbook)?  What question is being asked in the text?  Would a photo of the page help clarify your issues?

**Comment by shukryzablah** [comment]
A demonstration of the calculation behind a hypothesis test and a confidence interval. The relevant two pages are attached. (EX6.17 and EX6.18)

![20180717_134241](https://user-images.githubusercontent.com/28762146/42898565-7c2aaf6c-8a91-11e8-9b6d-ed7534294fca.jpg)
![20180717_134247](https://user-images.githubusercontent.com/28762146/42898564-7c18d116-8a91-11e8-9d79-cbffd097e2b5.jpg)

**Comment by nicholasjhorton** [comment]
Can you replicate the calculations by hand (as a function of the mean, sd, etc.) and using t.test()?

**Comment by shukryzablah** [comment]
yes
