### ISSUE TITLE
bargraph doesn't match 

### ISSUE THREAD

**Issue by shukryzablah** [Amherst-Statistics/IPS9inR#17]
## This is the bar graph that I want to match: 

![37407529_1610050225788906_7480943675048984576_n](https://user-images.githubusercontent.com/28762146/42951968-71e521e0-8b45-11e8-99a3-da48358a1127.png)

## And this is the bar graph I can make: 

``` r
suppressMessages(library(mosaic))
# this step is correct nvm it
Vaccine <- rbind(
  do(729) * data.frame(Required = "Yes", Party = "Democratic"),
  do(479) * data.frame(Required = "Yes", Party = "Republican"),
  do(230) * data.frame(Required = "No",  Party = "Democratic"), 
  do(258) * data.frame(Required = "No", Party = "Republican")
)  

gf_percents(~ Required, data = Vaccine, fill = ~ Party, position = "dodge")
```

![](https://i.imgur.com/mxKYRrt.png)

Created on 2018-07-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

## Bar graph is wanting to plot these percentages and I don't know how to get them: 

``` r
tally(Required ~ Party, data = Vaccine, margins = TRUE, format = "percent")
#>         Party
#> Required Democratic Republican
#>    Yes     76.01668   64.99322
#>    No      23.98332   35.00678
#>    Total  100.00000  100.00000
```

## How do I graph those percentages from tally from the Vaccine data set?

**Comment by nicholasjhorton** [comment]
I've fine with your default bar graph.  You can note that this is not an equivalent plot but that it provides the same info.
