### ISSUE TITLE
how to get confidence intervals in table? 

### ISSUE THREAD

**Issue by shukryzablah** [Amherst-Statistics/IPS9inR#18]
## This is the data
Five different numbers of facebook friends, there are n students in each group, each student gives a score.

``` r
library(readr)
Friends <- read_csv("https://nhorton.people.amherst.edu/ips9/data/chapter12/EG12-03FRIENDS.csv")
#> Parsed with column specification:
#> cols(
#>   Friends = col_integer(),
#>   Participant = col_integer(),
#>   Score = col_double()
#> )
Friends
#> # A tibble: 134 x 3
#>    Friends Participant Score
#>      <int>       <int> <dbl>
#>  1     102           1   3.8
#>  2     102           2   3.6
#>  3     102           3   3.2
#>  4     102           4   2.4
#>  5     102           5   4.8
#>  6     102           6   3  
#>  7     102           7   4.2
#>  8     102           8   3.6
#>  9     102           9   3.2
#> 10     102          10   3  
#> # ... with 124 more rows
```

Created on 2018-07-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

## I'm confused how to get those confidence interval values

![screenshot from 2018-07-19 16-31-16](https://user-images.githubusercontent.com/28762146/42968455-463ceae2-8b71-11e8-8f07-0df89ec614d9.png)

**Comment by nicholasjhorton** [comment]
How about:

> confint(lm(Score ~ 1, data = filter(Friends, Friends == 102)))

You need only give this for one of the groups, along with the output of

favstats(Score ~ Friends, data = Friends)
