### ISSUE TITLE
Flesh out remainder of website

### ISSUE THREAD

**Issue by sarahmcdonald20** [Amherst-Statistics/IPS9inR#2]

**Comment by nicholasjhorton** [comment]
see https://github.com/Amherst-Statistics/IPS9inR/commit/357d3d828ae6a4e9b0fc65d04d35478c50136247 for example of fixes to partIV.Rmd: other changes needed in parts I-III.

**Comment by bonnfire** [comment]
Got it! In the process of fixing right now.
