### ISSUE TITLE
Can't figure out how to add the vertical reference line

### ISSUE THREAD

**Issue by bonnfire** [Amherst-Statistics/IPS9inR#3]
Trying to overlay the sample mean on the distribution of bootstrapped means, but gf_vline() doesn't seem to cut it. Thoughts?

**Comment by bonnfire** [comment]
More specifically...
_mean_time_ is holding the sample mean here....
`
mean_time = FACE4 %>%
  pull(Time)` %>%
  mean()
`
while the `gf_vline()` function is taking it the value in as an argument for xintercept here: 
`
gf_histogram(~ mean, data = Avg_Viewtime) %>%
  gf_labs(x = "Bootstrapped Means", y = "Count") %>%
  gf_vline(xintercept = mean_time) 
` 
The class of mean_time is numeric, but when I use numbers like 0, or even the value 7.87, there is no issue for the line to appear. `gf_vline()` just doesn't seem to like this format.

**Comment by nicholasjhorton** [comment]
Can you please post a reproducible example?
