### ISSUE TITLE
ordering by count

### ISSUE THREAD

**Issue by bonnfire** [Amherst-Statistics/IPS9inR#9]
I want to create a barchart/histogram (?) of the counts of each category:
See reprex below: 
```
Online_data <- c(rep("Google", 406), rep("Library", 75), rep("Wikipedia", 52), rep("Other", 19))
gf_histogram(~ Online_data, Online_data, stat = "count")
```
However, I cannot get the gf_histogram() to order the count in a descending order

**Comment by nicholasjhorton** [comment]
Bonnie in future can you please include a pointer to the commit where you fixed this?
